
monthly_spreadsheet = "/Volumes/SanDisk Extreme SSD/Dropbox (ECA Consulting)/ECA Back Office/Lisa's Backup/Invoices/2021 Enrollment/March 2021.xlsx"

cci_programs = dict({
    "accounting professional": 2016,
    "amazon web services with cloud practitioner": 2050,
    "administrative assistant with quickbooks": 1748,
    "associate professional in human resources": 2095,
    "bookkeeping with quickbooks": 1733,
    "business management professional": 1948,
    "certified information system security professional": 2050,
    "childcare specialist": 1942,
    "clinical medical assistant": 1405,
    "clinical medical assistant with ob/gyn": 1405,
    "clinical medical assistant with pediatric specialist": 1405,
    "clinical medical assistant with pediatrics": 1405,
    "clinical medical assistant with ob/gyn-spanish": 1405,
    "clinical medical assistant (spanish)": 1405,
    "Clinical Medical Assistant Master": 0,
    "computer technician (comp tia a+)": 2050,
    "computer security technician (comp tia security+ and network +)": 2050,
    "computer support": 2050,
    "contract specialist": 2015,
    "criminal investigation professional": 2051,
    "diesel technician": 2050,
    "dental assisting": 1825,
    "ekg technician cert program": 1250,
    "entrepreneurship": 1905,
    "finanance professional": 1967,
    "finance professional": 1967,
    "front end web developer": 1850,
    "full stack web developer with ruby on rails": 1850,
    "full stack web developer with mean stack": 1850,
    "human resources professional": 2029,
    "it cyber security professional with comp tia security +": 2050,
    "it network professional with comptia netwrk+": 2050,
    "legal assistant certificate program with externship": 1788,
    "medical administration assistance": 1250,
    "medical administrative assistant": 1250,
    "medical administrative assistant online": 1250,
    "medical administrative assistant online": 1250,
    "medical billing and coding": 1215,
    "medical billing and coding with medical administrative assistant": 1370,
    "medical billing and coding with medical admin": 1370,
    "medical billing and coding with medical administration": 1370,
    "medical billing & coding w/ medical administrative assistant certificate program includes cmaa and cpc national certification exams": 1370,
    "massage practitioner program (500hr)": 3000,
    "massage practitioner program (750hr)": 3000,
    "marketing professional": 1972,
    "organizational behavior professional": 2090,
    "paralegal professional": 1699,
    "paralegal certificate program": 1699,
    "pharmacy technician": 1200,
    "pharmacy technician with medical administration": 1400,
    "pharmacy tech with med admin": 1400,
    "phlebotomy technician": 1575,
    "phlebotomy tech -spanish": 1575,
    "photography entrepreneur with adobe certificate": 1850,
    "photography entrepreneur with adobe": 1850,
    "physicians office assistant with ehrm": 1370,
    "Project management Professional": 1922,
    "Project Management Specialist for CAPM": 2033,
    "six sigma black belt (cssbb)": 1702,
    "teachers aide": 2029,
    "veterinary assistant specialist": 1013,
    "welding technician": 2050})

commission = dict({
    "accounting professional": 500,
    "administrative assistant with quickbooks": 500,
    "bookkeeping with quickbooks": 400,
    "child day care management cert program": 400,
    "childcare specialist": 500,
    "clinical medical assistant": 300,
    "clinical medical assistant with ob/gyn": 300,
    "clinical medical assistant with pediatric specialist": 300,
    "criminal investigation professional": 500,
    "dental assisting certification": 400,
    "dental assisting": 400,
    "life skills coach": 300,
    "ekg technician cert program": 300,
    "event planning entrepreneur": 300,
    "finanance professional": 500,
    "full stack web developer with mean stack": None,
    "human resources professional": 500,
    "it cyber security professional with comp tia security +": 500,
    "medical administration assistance": None,
    "medical billing and coding": 300,
    "medical billing and coding with medical administration": 300,
    "medical billing and coding with medical admin": 300,
    "medical billing and coding with medical administration": 300,
    "medical billing & coding w/ medical administrative assistant certificate program includes cmaa and cpc national certification exams": 300,
    "mental health technician specialist cert": 400,
    "paralegal": 500,
    "pharmacy technician": 300,
    "pharmacy technician with medical administration": 300,
    "phlebotomy technician": 500,
    "photography entrepreneur with adobe certificate": 300,
    "photography entrepreneur with adobe": 300,
    "patient advocate specialist": 400,
    "teachers aide": 500,
    "veterinary assistant specialist": 300
})

au_programs = dict({
    "clinical medical assistant": 1405,
    "clinical medical assistant with ob/gyn": 1405,
    "clinical medical assistant with obgyn": 1405,
    "Clinical Medical Assistant with OBGYN": 1405,
    "clinical medical assistant with pediatric specialist": 1405,
    "clinical medical assistant with pediatrics": 1405,
    "clinical medical assistant master with externship": 1405,
    "dental assisting": 1825,
    "ekg technician cert program": 1250,
    "electronic health records management (ehrm)": 1575,
    "electronic health records management": 1575,
    "medical administrative assistant": 1250,
    "medical billing and coding": 1215,
    "medical billing and coding with medical administrative assistant": 1370,
    "medical billing and coding with medical admin": 1370,
    "medical billing and coding with medical administration": 1370,
    "medical billing & coding w/ medical administration": 1370,
    "medical billing & coding w/ medical administrative assistant certificate program includes cmaa and cpc national certification exams": 1370,
    "personal care assistant": 1575,
    "pharmacy technician": 1200,
    "pharmacy technician with medical administration": 1400,
    "pharmacy technician with medical admin online inc. national cert. and clinical ext.": 1400,
    "phlebotomy technician": 1575,
    "physicians office assistant with ehrm": 1370,
    "veterinary assistant specialist": 1013, })

met_programs = dict({
    "accounting professional": 2999.25,
    "administrative assistant with quickbooks": 2999.25,
    "administrative assistant with bookkeeping and quickbooks": 2999.25,
    "amazon web services certified solutions architect": 2250,
    "associate professional in human resources": 2999.25,
    "bookeeping with quickbooks": 2849.25,
    "business management professional": 2999.25,
    "childcare specialist": 2999.25,
    "child day care management cert program": 2962.50,
    "computer security technician (comp tia security+ and network +)": 2999.25,
    "computer technician (comp tia a+)": 2999.25,
    "drug and alcohol counselor": 2962.50,
    "event planning entrepreneur": 2962.50,
    "event panning and banquet management": 2962.50,
    "full stack web developer with mean stack": 2999.25,
    "full stack web developer with ruby on rails": 2999.25,
    "front end web developer": 2999.25,
    "health & fitness industry professional": 2962.50,
    "homeland security specialist": 2849.25,
    "human resources professional": 2999.25,
    "interior decorating and design entrepreneur": 2962.50,
    "it cyber security professional with comp tia security+": 2999.25,
    "it network professional with comptia network+": 2999.25,
    "legal transcription specialist": 2962.50,
    "legal assistant": 2849.25,
    "life skills coach": 2962.50,
    "massage practitioner program (500 hr)": 3000,
    "massage practitioner program (620 hr)": 3000,
    "massage practitioner program (650 hr)": 3000,
    "massage practitioner program (700 hr)": 3000,
    "massage practitioner program (750 hr)": 3000,
    "marketing professional": 2849.25,
    "mental health technician specialist cert": 2962.50,
    "nutrition and fitness professional": 2962.50,
    "ophthalmic assistant specialist": 2962.50,
    "paralegal certificate program": 2999.25,
    "patient advocate specialist": 2962.50,
    "personal fitness trainer specialist": 2999.25,
    "photography entrepreneur with adobe certificate": 2962.50,
    "photography entrepreneur with adobe": 2962.50,
    "physical therapy aide": 2962.50,
    "professional cooking and catering": 2962.50,
    "project management professional (pmp)": 2999.25,
    "real estate law professional": 2849.25,
    "stress management coach": 2962.50,
    "teachers aide": 2999.25,
    "technical writing": 1649.25,
    "travel agent specialist": 2962.50,
    'veterinary office assistant specialist': 2962.50,
    "virtual assistant associate": 2962.50,
    "wedding consultant entrepreneur": 2962.50,
    "wellness coaching": 2437.50,
    "wellness and life skills coaching specialist": 3000})

uwlax_programs = dict({
    "associate professional in human resources": 2799.30,
    "clinical medical assistant": 2765,
    "dental assisting": 2765,
    "dental assisting certification": 2765,
    "ekg technician": 2100,
    "electronic health records management": 2100,
    "medical administrative assistant": 2100,
    "medical billing and coding with medical admin": 2765,
    "paralegal certificate program": 2799.30,
    "pharmacy technician with medical administration": 2765,
    "physicians office assistant with ehrm": 2765,
    "teachers aide": 2799.30,
    "veterinary assistant": 2695})

csu_programs = dict({
    "administrative assisitant with bookkeeping and quickbooks": 2999.25,
    "clinical medical assistant": 2962.50,
    "human resources professional": 2999.25,
    "medical billing and coding": 2437.50,
    "medical billing and coding with medical administration": 2962.50,
    "paralegal": 2999.25,
    "pharmacy technician": 2250})

tamut_ed4_programs = dict({
    "interior decorating and design entrepreneur": 2999,
    "virtual assistant associate": 2999,
    "medical inpatient auditing": 2750,
    "wellness & life skills coaching specialist": 2999
})
